Somewhat loosen the types for the standard binding handlers.
knockout-lint/knockout-lint pull request #78
Opened 2020-11-12 22:16 UTC by maskmaster

Allow observable variables to be bound to all standard binding handlers. Also adjust the allowed types for the css and style bindings.

2020-11-13 07:34 UTC, tscpp commented
If valueaccessor unwrap observables, approved. If not, not approved.

2020-11-13 07:41 UTC, maskmaster commented
Valueaccessor does not unwrap. I think it is the responsibility for each binding handler to do if they allow observables to be bound. The normal behaviour in a binding handler is to unwrap the result of the valueaccessor-call.
See example from knockouts documentation on custom binding handlers
```javascript
ko.bindingHandlers.slideVisible = {
    update: function(element, valueAccessor, allBindings) {
        // First get the latest data that we're bound to
        var value = valueAccessor();
 
        // Next, whether or not the supplied model property is observable, get its current value
        var valueUnwrapped = ko.unwrap(value);
```
This means that custom bindinghandlers that does not accept observables cannot use the `BindingContextIdentityTransform` that we use.

2020-11-13 08:31 UTC, tscpp commented
I think it is the responsibility of each binding handler to use `ko.MaybeObservable` on the type. Else, the binding handler won't accept observables.

When using an observable, the observable should be called and not sent into the binding handler as an observable, if not an observable, is wanted.

2020-11-14 10:00 UTC, tscpp requested changes

2020-11-14 10:00 UTC, tscpp commented on lib/context.d.ts
> +	style: BindingContextIdentityTransform<Record<string, MaybeReadonlyObservable<string | number>>>
Using numbers as the value in the 'style' binding handler is not supported.

```suggestion
	style: BindingContextIdentityTransform<Record<string, MaybeReadonlyObservable<string>>>
```

2020-11-14 10:07 UTC, tscpp requested changes
Add changes to CHANGELOG.md, if any noticeably changed, which may not the case here. Let me know when you are finished.

2020-11-14 10:11 UTC, tscpp commented
Oops

2020-11-14 10:15 UTC, closed without merging